build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
args:
  GITHUB_REPO: "https://github.com/TunerDav/reminder-app.git"
  GITHUB_BRANCH: "main"
  CACHEBUST: "v1.1.8"
labels:
  org.opencontainers.image.title: "Reminder App"
  org.opencontainers.image.description: "Family relationship manager with reminders, events and contacts"
  org.opencontainers.image.source: "https://github.com/TunerDav/reminder-app"
  org.opencontainers.image.licenses: "MIT"
